# Generated by Django 4.0.5 on 2022-06-27 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sbranch',
            fields=[
                ('branches', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('credits', models.IntegerField(blank=True, null=True)),
                ('no_of_courses', models.IntegerField()),
            ],
            options={
                'db_table': 'sbranch',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Scourse',
            fields=[
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=20)),
                ('credit', models.IntegerField()),
            ],
            options={
                'db_table': 'scourse',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Steacher',
            fields=[
                ('teacher_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=20)),
                ('contact', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'steacher',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('fathers_name', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(max_length=30)),
                ('mothers_name', models.CharField(blank=True, max_length=20, null=True)),
                ('total_years', models.IntegerField(blank=True, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('branch', models.ForeignKey(db_column='branch', on_delete=django.db.models.deletion.DO_NOTHING, to='app.sbranch')),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ucs444Est',
            fields=[
                ('roll_no', models.OneToOneField(db_column='roll_no', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.student')),
                ('maximum_marks', models.IntegerField(blank=True, null=True)),
                ('obtained_marks', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ucs444_est',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ucs444Mst',
            fields=[
                ('roll_no', models.OneToOneField(db_column='roll_no', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.student')),
                ('maximum_marks', models.IntegerField(blank=True, null=True)),
                ('obtained_marks', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ucs444_mst',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ucs444Sessional',
            fields=[
                ('roll_no', models.OneToOneField(db_column='roll_no', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.student')),
                ('maximum_marks', models.IntegerField(blank=True, null=True)),
                ('obtained_marks', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ucs444_sessional',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ucs768Est',
            fields=[
                ('roll_no', models.OneToOneField(db_column='roll_no', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.student')),
                ('maximum_marks', models.IntegerField(blank=True, null=True)),
                ('obtained_marks', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ucs768_est',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ucs768Mst',
            fields=[
                ('roll_no', models.OneToOneField(db_column='roll_no', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.student')),
                ('maximum_marks', models.IntegerField(blank=True, null=True)),
                ('obtained_marks', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ucs768_mst',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ucs768Sessional',
            fields=[
                ('roll_no', models.OneToOneField(db_column='roll_no', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.student')),
                ('maximum_marks', models.IntegerField(blank=True, null=True)),
                ('obtained_marks', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ucs768_sessional',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Steach',
            fields=[
                ('iddd', models.AutoField(primary_key=True, serialize=False)),
                ('branches', models.ForeignKey(blank=True, db_column='branches', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.sbranch')),
                ('course_code', models.ForeignKey(blank=True, db_column='course_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.scourse')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.steacher')),
            ],
            options={
                'db_table': 'steach',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Slib',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField(blank=True, null=True)),
                ('book_name', models.CharField(max_length=30)),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('roll_no', models.ForeignKey(blank=True, db_column='roll_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.student')),
            ],
            options={
                'db_table': 'slib',
                'managed': True,
                'unique_together': {('issue_date', 'book_id')},
            },
        ),
        migrations.CreateModel(
            name='Sfine',
            fields=[
                ('fine', models.IntegerField(blank=True, null=True)),
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.slib')),
                ('fine_paid', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=10, null=True)),
                ('roll_n0', models.ForeignKey(blank=True, db_column='roll_n0', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.student')),
            ],
            options={
                'db_table': 'sfine',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('idd', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('branches', models.ForeignKey(blank=True, db_column='branches', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.sbranch')),
                ('course_code', models.ForeignKey(blank=True, db_column='course_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.scourse')),
            ],
            options={
                'db_table': 'semester',
                'managed': True,
                'unique_together': {('course_code', 'semester', 'branches')},
            },
        ),
    ]
